<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJlsgCB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJlsgCB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWJlsgCB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWJlsgCB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWJlsgCB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WJlsgCB',
    'container.build_id' => '6cb920b7',
    'container.build_time' => 1554067220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJlsgCB');
