<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSByTgUK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSByTgUK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSByTgUK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSByTgUK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSByTgUK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SByTgUK',
    'container.build_id' => '1500a487',
    'container.build_time' => 1553880134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSByTgUK');
